name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Run tests and generate coverage
      - name: Test
        run: |
          docker build --tag ngx-mdx .

          docker run --rm \
            --volume "$PWD:/opt/tmp" \
            --user "$(id -u):$(id -g)" \
            ngx-mdx cp --recursive /opt/app/coverage /opt/tmp

      # Export code coverage statistics
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage/ngx-mdx/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          name: ngx-mdx
